# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 68c140ed1567cf02f42674a9078ed4adf261c2ad9faaa6e955bbc20b7020bcb7ebac14ef8d1d44ccaf56b193fc2d02ea784693cfccb1972ac4dd343a9e2372b8

test:
  secret_key_base: a0282e0bf518252ad28ae6689999b3ebae44c72608eb3a42c419a1ec463cb0beecfa5c818f1ab2ed94db8f46f40f3856344e91478f2c105e8e550893562a7ce9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
